In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os
Firms = "/content/drive/MyDrive/India_Firms"
os.listdir(Firms)

['fire_archive_SV-C2_800831.csv',
 'fire_nrt_J2V-C2_810478.csv',
 'fire_archive_J1V-C2_810477.csv',
 'fire_nrt_J1V-C2_810477.csv']

In [4]:
import pandas as pd

In [5]:
df1 = pd.read_csv(f"{Firms}/fire_nrt_J2V-C2_810478.csv")
df3 = pd.read_csv(f"{Firms}/fire_archive_SV-C2_800831.csv")

In [6]:
df2 = pd.read_csv(f"{Firms}/fire_archive_J1V-C2_810477.csv")

In [14]:
df2

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,22.41149,92.65405,330.42,0.63,0.72,2018-04-01,606,N20,VIIRS,l,2,300.69,3.30,D,0
1,22.50408,92.55746,346.15,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,298.87,10.10,D,0
2,22.50259,92.55136,330.26,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.59,8.80,D,0
3,22.58846,92.51312,337.59,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.01,6.89,D,0
4,22.58705,92.50738,329.40,0.63,0.72,2018-04-01,606,N20,VIIRS,n,2,299.01,7.35,D,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5107278,21.92633,85.22395,308.86,0.53,0.42,2026-06-30,2020,N20,VIIRS,n,2,282.16,1.71,N,2
5107279,21.91897,83.35211,300.18,0.43,0.38,2026-06-30,2020,N20,VIIRS,n,2,268.80,1.05,N,2
5107280,13.08136,79.97861,305.94,0.40,0.37,2026-06-30,2022,N20,VIIRS,n,2,285.99,1.63,N,2
5107281,11.81606,77.91790,308.89,0.39,0.36,2026-06-30,2023,N20,VIIRS,n,2,288.09,0.95,N,2
5107282,11.80837,77.92383,307.88,0.38,0.36,2026-06-30,2023,N20,VIIRS,n,2,287.50,1.24,N,2

In [15]:
df1

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,21.95337,87.52301,334.68,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.20,7.20,D
1,22.13076,88.77950,328.67,0.35,0.57,2024-01-17,635,N21,VIIRS,n,2.0NRT,292.46,2.18,D
2,21.95212,87.52202,341.53,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.39,7.36,D
3,23.81528,92.59270,332.27,0.57,0.43,2024-01-17,635,N21,VIIRS,n,2.0NRT,293.78,5.13,D
4,22.41985,88.27590,326.11,0.37,0.58,2024-01-17,635,N21,VIIRS,n,2.0NRT,290.04,9.03,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1657691,10.41422,77.11642,320.12,0.51,0.41,2026-08-31,2008,N21,VIIRS,n,2.0NRT,290.43,2.48,N
1657692,9.06696,77.89515,314.44,0.45,0.39,2026-08-31,2008,N21,VIIRS,n,2.0NRT,295.57,0.92,N
1657693,30.18717,74.48603,305.14,0.57,0.69,2026-08-31,2142,N21,VIIRS,n,2.0NRT,289.73,1.24,N
1657694,22.38330,73.11890,311.62,0.73,0.76,2026-08-31,2144,N21,VIIRS,n,2.0NRT,268.93,2.43,N
1657695,22.39004,73.12098,309.44,0.73,0.76,2026-08-31,2144,N21,VIIRS,n,2.0NRT,270.65,4.01,N

In [17]:
df3.sample(30)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
6354200,30.51394,76.24624,343.58,0.57,0.43,2022-11-07,822,SNPP,SNPP,n,2,301.40,28.83,D,0
8249377,14.83597,76.03194,342.75,0.40,0.37,2026-01-18,822,SNPP,SNPP,n,2,309.07,3.82,D,0
2100617,20.26816,75.10640,332.61,0.53,0.42,2015-12-18,755,SNPP,SNPP,n,2,301.32,3.42,D,0
5799403,25.83782,81.00075,336.75,0.51,0.66,2021-11-14,833,SNPP,SNPP,n,2,297.79,5.06,D,0
3454586,29.68357,78.14957,330.84,0.36,0.58,2018-02-07,833,SNPP,SNPP,n,2,297.31,2.47,D,0
5715140,30.09611,76.32264,340.96,0.45,0.63,2021-10-23,847,SNPP,SNPP,n,2,296.99,4.14,D,0
310143,23.35924,77.34645,351.44,0.56,0.51,2012-04-11,830,SNPP,SNPP,n,2,316.28,16.77,D,0
1554756,30.57769,76.31086,341.26,0.45,0.63,2014-11-05,854,SNPP,SNPP,n,2,298.44,5.61,D,0
7469863,31.53907,74.61084,333.95,0.39,0.36,2024-10-12,801,SNPP,SNPP,n,2,300.71,14.04,D,0
4553447,22.91961,79.84852,336.06,0.49,0.49,2019-11-15,819,SNPP,SNPP,n,2,305.58,5.98,D,0
2922597,21.51689,73.03680,346.04,0.45,0.47,2017-03-10,753,SNPP,SNPP,n,2,308.90,15.33,D,0
968242,29.66160,75.77002,334.68,0.51,0.41,2013-10-15,744,SNPP,SNPP,n,2,304.68,4.96,D,0
2792029,28.31507,78.50137,327.57,0.49,0.40,2016-12-24,2046,SNPP,SNPP,n,2,282.49,2.46,N,0
3369386,25.44005,83.85967,346.90,0.60,0.70,2017-11-30,826,SNPP,SNPP,n,2,298.66,7.09,D,0
7432080,24.64467,84.16447,340.89,0.42,0.38,2024-05-22,741,SNPP,SNPP,n,2,305.74,9.23,D,0
5432614,23.73841,77.94737,356.33,0.48,0.65,2021-03-29,843,SNPP,SNPP,n,2,316.10,5.43,D,0
5653988,16.62648,77.16022,344.95,0.43,0.46,2021-05-06,829,SNPP,SNPP,n,2,305.94,8.91,D,0
5483753,23.18993,82.42450,307.38,0.39,0.37,2021-04-01,2014,SNPP,SNPP,n,2,291.22,0.54,N,0
6016515,23.76324,82.43907,349.62,0.47,0.40,2022-03-24,754,SNPP,SNPP,n,2,308.94,5.77,D,0
2166746,20.25263,81.92507,305.61,0.54,0.42,2016-02-09,2030,SNPP,SNPP,n,2,292.48,1.87,N,0
834282,19.79730,83.92001,342.65,0.53,0.50,2013-04-10,804,SNPP,SNPP,n,2,301.12,28.99,D,0
5473462,18.24442,78.09333,344.93,0.49,0.40,2021-04-01,745,SNPP,SNPP,l,2,317.35,10.24,D,0
7696868,21.31171,83.31900,341.58,0.40,0.44,2025-03-05,800,SNPP,SNPP,l,2,313.95,4.95,D,0
2732861,30.54674,74.30827,367.00,0.34,0.56,2016-11-10,847,SNPP,SNPP,h,2,307.61,18.86,D,0
4923509,24.54122,77.79628,332.35,0.62,0.54,2020-10-19,723,SNPP,SNPP,n,2,294.82,4.85,D,0
4425764,30.37415,75.76235,344.53,0.45,0.39,2019-05-18,814,SNPP,SNPP,n,2,307.08,3.19,D,0
1630747,29.19721,77.59041,328.87,0.53,0.42,2014-12-30,822,SNPP,SNPP,n,2,293.58,3.41,D,0
7246658,26.96740,82.27280,336.86,0.50,0.66,2024-04-07,827,SNPP,SNPP,n,2,302.40,4.03,D,0
6561914,17.75928,82.07240,330.82,0.40,0.37,2023-03-01,741,SNPP,SNPP,l,2,303.83,21.05,D,0
5059544,22.03071,83.02882,333.39,0.39,0.36,2020-12-16,734,SNPP,SNPP,n,2,297.68,3.24,D,0

In [18]:
df3['type'].unique()

array([0, 2, 3, 1])

In [19]:
df3.head(10)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,10.41351,79.31155,337.55,0.36,0.58,2012-01-20,724,SNPP,SNPP,n,2,300.05,1.52,D,0
1,8.29971,77.60221,333.41,0.52,0.67,2012-01-20,724,SNPP,SNPP,n,2,295.45,4.63,D,0
2,10.67030,78.50605,331.51,0.41,0.61,2012-01-20,724,SNPP,SNPP,n,2,300.56,1.14,D,0
3,13.07316,77.29248,334.82,0.45,0.63,2012-01-20,725,SNPP,SNPP,n,2,299.53,2.56,D,0
4,12.82314,75.97828,335.76,0.55,0.68,2012-01-20,725,SNPP,SNPP,n,2,301.16,5.61,D,0
5,13.55270,76.71556,339.92,0.48,0.64,2012-01-20,725,SNPP,SNPP,n,2,298.42,4.98,D,0
6,14.02895,77.46936,330.12,0.42,0.61,2012-01-20,725,SNPP,SNPP,l,2,304.59,1.40,D,0
7,14.27903,78.48937,336.77,0.35,0.57,2012-01-20,725,SNPP,SNPP,n,2,310.18,2.74,D,0
8,14.54344,79.06084,331.52,0.32,0.55,2012-01-20,725,SNPP,SNPP,n,2,301.46,1.94,D,0
9,14.54332,79.06203,339.64,0.32,0.55,2012-01-20,725,SNPP,SNPP,n,2,302.09,3.26,D,0

In [7]:
df3 = df3.drop(columns=['type'])

In [8]:
df2 = df2.drop(columns=['type'])

In [9]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

print(df1.columns.tolist())
print(df2.columns.tolist())
print(df3.columns.tolist())

(1657696, 14)
(5107283, 14)
(8627741, 14)
['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date', 'acq_time', 'satellite', 'instrument', 'confidence', 'version', 'bright_t31', 'frp', 'daynight']
['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date', 'acq_time', 'satellite', 'instrument', 'confidence', 'version', 'bright_t31', 'frp', 'daynight']
['latitude', 'longitude', 'brightness', 'scan', 'track', 'acq_date', 'acq_time', 'satellite', 'instrument', 'confidence', 'version', 'bright_t31', 'frp', 'daynight']

In [10]:
import gc

In [11]:
combined_df = pd.concat(
    [df1, df2, df3],
    ignore_index=True,
    copy=False
)

del df1, df2, df3
gc.collect()

0

In [12]:
combined_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight
0,21.95337,87.52301,334.68,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.20,7.20,D
1,22.13076,88.77950,328.67,0.35,0.57,2024-01-17,635,N21,VIIRS,n,2.0NRT,292.46,2.18,D
2,21.95212,87.52202,341.53,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.39,7.36,D
3,23.81528,92.59270,332.27,0.57,0.43,2024-01-17,635,N21,VIIRS,n,2.0NRT,293.78,5.13,D
4,22.41985,88.27590,326.11,0.37,0.58,2024-01-17,635,N21,VIIRS,n,2.0NRT,290.04,9.03,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15392715,21.10543,72.63224,311.68,0.45,0.63,2026-04-27,2140,SNPP,SNPP,n,2,295.36,1.46,N
15392716,21.10446,72.63651,315.12,0.45,0.63,2026-04-27,2140,SNPP,SNPP,n,2,295.65,1.46,N
15392717,20.90905,71.45824,313.77,0.38,0.59,2026-04-27,2140,SNPP,SNPP,n,2,296.55,1.39,N
15392718,18.77475,73.74735,307.67,0.59,0.70,2026-04-27,2140,SNPP,SNPP,n,2,290.82,1.02,N
15392719,18.68412,73.02840,306.50,0.53,0.67,2026-04-27,2140,SNPP,SNPP,n,2,294.02,2.31,N

In [13]:
print("\nMissing values:")
print(combined_df[
    ["latitude", "longitude", "acq_date", "acq_time"]
].isna().sum())

Missing values:
latitude     0
longitude    0
acq_date     0
acq_time     0
dtype: int64

In [14]:
exact_duplicates = combined_df.duplicated()

print("Exact duplicate rows:", exact_duplicates.sum())

Exact duplicate rows: 0

# CREATING **TIMESTAMP**

In [15]:
combined_df['datetime'] = pd.to_datetime(
    combined_df['acq_date'].astype(str) + ' ' +
    combined_df['acq_time'].astype(str).str.zfill(4),
    format='%Y-%m-%d %H%M',
    errors='coerce'
)

In [16]:
combined_df['date'] = combined_df['datetime'].dt.date

In [17]:
import geopandas as gpd

gdf = gpd.GeoDataFrame(
    combined_df,
    geometry=gpd.points_from_xy(
        combined_df.longitude,
        combined_df.latitude
    ),
    crs='EPSG:4326'
)

In [18]:
print(gdf.shape)
print(gdf.crs)
print(gdf[['latitude', 'longitude', 'datetime']].head())

(15392720, 17)
EPSG:4326
   latitude  longitude            datetime
0  21.95337   87.52301 2024-01-17 06:35:00
1  22.13076   88.77950 2024-01-17 06:35:00
2  21.95212   87.52202 2024-01-17 06:35:00
3  23.81528   92.59270 2024-01-17 06:35:00
4  22.41985   88.27590 2024-01-17 06:35:00

In [19]:
import numpy as np
from pyproj import Transformer

# Transformer: WGS84 lat/lon -> EPSG:6933
transformer = Transformer.from_crs(
    "EPSG:4326",
    "EPSG:6933",
    always_xy=True
)

# Convert directly to projected X/Y
x, y = transformer.transform(
    combined_df['longitude'].to_numpy(),
    combined_df['latitude'].to_numpy()
)

print(x[:5])
print(y[:5])

[8444769.67126202 8566003.71753447 8444674.14984457 8933925.20138718
 8517413.22680011]
[2734343.02601368 2755358.77833876 2734194.84478418 2953611.65280736
 2789552.40399693]

In [37]:
combined_df.sample(12)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,datetime,date
7758594,30.54587,76.20655,347.77,0.57,0.43,2013-10-29,822,SNPP,SNPP,n,2,308.28,35.46,D,2013-10-29 08:22:00,2013-10-29
11776322,23.63306,85.63171,299.30,0.56,0.43,2020-11-10,1937,SNPP,SNPP,n,2,288.31,0.57,N,2020-11-10 19:37:00,2020-11-10
13949237,19.20318,80.52231,331.96,0.40,0.44,2024-03-28,812,SNPP,SNPP,l,2,304.66,3.80,D,2024-03-28 08:12:00,2024-03-28
9290201,23.20306,79.05446,349.50,0.54,0.42,2016-04-25,736,SNPP,SNPP,l,2,319.66,14.59,D,2016-04-25 07:36:00,2016-04-25
540384,21.51616,72.95297,338.40,0.73,0.76,2025-01-22,722,N21,VIIRS,n,2.0NRT,297.48,6.33,D,2025-01-22 07:22:00,2025-01-22
1411108,19.79414,80.18858,308.01,0.40,0.37,2026-04-08,2023,N21,VIIRS,n,2.0NRT,295.03,2.20,N,2026-04-08 20:23:00,2026-04-08
6838612,17.19418,77.38290,338.33,0.58,0.70,2012-02-27,714,SNPP,SNPP,n,2,310.55,3.84,D,2012-02-27 07:14:00,2012-02-27
7375008,21.90357,86.85411,332.30,0.43,0.38,2013-01-27,732,SNPP,SNPP,l,2,306.69,2.81,D,2013-01-27 07:32:00,2013-01-27
14754465,24.59331,79.70464,367.00,0.41,0.37,2025-04-23,742,SNPP,SNPP,l,2,327.02,5.78,D,2025-04-23 07:42:00,2025-04-23
5995964,24.34205,79.62755,355.94,0.39,0.44,2025-04-25,727,N20,VIIRS,l,2,325.95,4.02,D,2025-04-25 07:27:00,2025-04-25
8813078,30.75360,75.44080,356.90,0.40,0.60,2015-11-08,849,SNPP,SNPP,l,2,292.54,21.46,D,2015-11-08 08:49:00,2015-11-08
6139707,23.75872,86.40292,310.37,0.39,0.36,2025-11-19,1956,N20,VIIRS,n,2,292.08,1.17,N,2025-11-19 19:56:00,2025-11-19

In [38]:
combined_df.duplicated().sum()

np.int64(0)

In [39]:
duplicate_cols = [
    "latitude",
    "longitude",
    "acq_date",
    "acq_time",
    "satellite"
]

duplicate_count = combined_df.duplicated(
    subset=duplicate_cols,
    keep=False
).sum()

print(duplicate_count)

12

In [40]:


duplicates = combined_df[
    combined_df.duplicated(
        subset=duplicate_cols,
        keep=False
    )
].sort_values(duplicate_cols)

print(duplicates[
    [
        "latitude",
        "longitude",
        "brightness",
        "scan",
        "track",
        "acq_date",
        "acq_time",
        "satellite",
        "instrument",
        "confidence",
        "version",
        "bright_t31",
        "frp",
        "daynight",
        "datetime"
    ]
].to_string(index=False))

 latitude  longitude  brightness  scan  track   acq_date  acq_time satellite instrument confidence version  bright_t31   frp daynight            datetime
 22.52859   82.90852      307.18  0.59   0.53 2021-03-28      2040       N20      VIIRS          n       2      294.12  3.02        N 2021-03-28 20:40:00
 22.52859   82.90852      306.19  0.59   0.53 2021-03-28      2040       N20      VIIRS          n       2      293.94  3.74        N 2021-03-28 20:40:00
 23.55932   78.56985      307.52  0.52   0.67 2026-04-13      1940       N20      VIIRS          n       2      288.79  1.56        N 2026-04-13 19:40:00
 23.55932   78.56985      309.10  0.52   0.67 2026-04-13      1940       N20      VIIRS          n       2      289.01  1.03        N 2026-04-13 19:40:00
 23.80967   92.42800      335.77  0.41   0.60 2025-03-10       741       N21      VIIRS          n  2.0NRT      300.91  5.44        D 2025-03-10 07:41:00
 23.80967   92.42800      339.61  0.41   0.60 2025-03-10       741       N21      VIIRS          n  2.0NRT      301.45 25.59        D 2025-03-10 07:41:00
 25.17081   93.48524      367.00  0.59   0.70 2025-03-06       601      SNPP       SNPP          h       2      299.74 55.45        D 2025-03-06 06:01:00
 25.17081   93.48524      367.00  0.59   0.70 2025-03-06       601      SNPP       SNPP          h       2      300.33 45.11        D 2025-03-06 06:01:00
 25.68258   79.85294      343.45  0.34   0.56 2024-05-09       826      SNPP       SNPP          n       2      307.68  2.30        D 2024-05-09 08:26:00
 25.68258   79.85294      343.16  0.34   0.56 2024-05-09       826      SNPP       SNPP          n       2      307.91  1.53        D 2024-05-09 08:26:00
 26.67010   91.01898      349.28  0.40   0.60 2016-01-08       622      SNPP       SNPP          n       2      292.74  5.63        D 2016-01-08 06:22:00
 26.67010   91.01898      349.06  0.40   0.60 2016-01-08       622      SNPP       SNPP          n       2      292.60  5.81        D 2016-01-08 06:22:00

In [ ]:
# Remove only completely identical rows #abhi remove krne ki jarurat nhi hai baki ke components jaruri hai

combined_df = combined_df.drop_duplicates().reset_index(drop=True)

print("Remaining records:", len(combined_df))

In [ ]:
duplicate_count = combined_df.duplicated(
    subset=duplicate_cols,
    keep=False
).sum()

print(duplicate_count)

In [20]:
combined_df["x"] = x
combined_df["y"] = y

In [21]:
combined_df

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,datetime,date,x,y
0,21.95337,87.52301,334.68,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.20,7.20,D,2024-01-17 06:35:00,2024-01-17,8.444770e+06,2.734343e+06
1,22.13076,88.77950,328.67,0.35,0.57,2024-01-17,635,N21,VIIRS,n,2.0NRT,292.46,2.18,D,2024-01-17 06:35:00,2024-01-17,8.566004e+06,2.755359e+06
2,21.95212,87.52202,341.53,0.42,0.61,2024-01-17,635,N21,VIIRS,n,2.0NRT,291.39,7.36,D,2024-01-17 06:35:00,2024-01-17,8.444674e+06,2.734195e+06
3,23.81528,92.59270,332.27,0.57,0.43,2024-01-17,635,N21,VIIRS,n,2.0NRT,293.78,5.13,D,2024-01-17 06:35:00,2024-01-17,8.933925e+06,2.953612e+06
4,22.41985,88.27590,326.11,0.37,0.58,2024-01-17,635,N21,VIIRS,n,2.0NRT,290.04,9.03,D,2024-01-17 06:35:00,2024-01-17,8.517413e+06,2.789552e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15392715,21.10543,72.63224,311.68,0.45,0.63,2026-04-27,2140,SNPP,SNPP,n,2,295.36,1.46,N,2026-04-27 21:40:00,2026-04-27,7.008015e+06,2.633535e+06
15392716,21.10446,72.63651,315.12,0.45,0.63,2026-04-27,2140,SNPP,SNPP,n,2,295.65,1.46,N,2026-04-27 21:40:00,2026-04-27,7.008427e+06,2.633420e+06
15392717,20.90905,71.45824,313.77,0.38,0.59,2026-04-27,2140,SNPP,SNPP,n,2,296.55,1.39,N,2026-04-27 21:40:00,2026-04-27,6.894740e+06,2.610107e+06
15392718,18.77475,73.74735,307.67,0.59,0.70,2026-04-27,2140,SNPP,SNPP,n,2,290.82,1.02,N,2026-04-27 21:40:00,2026-04-27,7.115607e+06,2.353611e+06
15392719,18.68412,73.02840,306.50,0.53,0.67,2026-04-27,2140,SNPP,SNPP,n,2,294.02,2.31,N,2026-04-27 21:40:00,2026-04-27,7.046239e+06,2.342646e+06

In [22]:
SPATIAL_THRESHOLD = 1000       # metres
TEMPORAL_THRESHOLD = 12        # hours

In [23]:
TEMPORAL_THRESHOLD_SECONDS = (
    TEMPORAL_THRESHOLD * 60 * 60
)

In [24]:
combined_df["grid_x"] = np.floor(
    combined_df["x"] / SPATIAL_THRESHOLD
).astype("int32")

combined_df["grid_y"] = np.floor(
    combined_df["y"] / SPATIAL_THRESHOLD
).astype("int32")

In [25]:
combined_df["time_seconds"] = (
    combined_df["datetime"].astype("int64") // 10**9
)

In [26]:
combined_df["time_bin"] = (
    combined_df["time_seconds"] //
    TEMPORAL_THRESHOLD_SECONDS
).astype("int64")

In [27]:
print(combined_df.shape)
print(combined_df["date"].value_counts().head(20))

(15392720, 22)
date
2021-03-31    37801
2021-04-01    36359
2025-03-29    35321
2021-03-30    33403
2021-03-06    33035
2026-04-22    32363
2021-03-27    32258
2025-03-30    30473
2025-03-06    29986
2025-03-28    29953
2021-04-02    29842
2025-03-27    29452
2026-04-21    28456
2025-03-18    28447
2026-04-14    28151
2021-03-29    27979
2021-03-26    27458
2025-03-07    27051
2026-04-15    26684
2021-03-07    26585
Name: count, dtype: int64

In [29]:
combined_df['version']= combined_df['version'].astype("string")

output_path = "/content/drive/MyDrive/India_Firms/India_Firms.parquet"

combined_df.to_parquet(output_path, index=False)

print("Saved successfully!")
print(output_path)

Saved successfully!
/content/drive/MyDrive/India_Firms/India_Firms.parquet